sudo: required
language: c
os:
  - linux
compiler:
  - gcc

script:
  - cc main.c -coverage
  - ./a.out
  - gcov -o test.c csv.c list.c
  - echo program compiled successfully

after_success:
  - bash <(curl -s https://codecov.io/bash)