before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check
  - sudo apt-get install lcov

sudo: required
language: c
os:
  - linux
compiler:
  - gcc


before_script:  
  - cmake .

script: 
  - make 
  - make test
  - lcov --directory . --capture --output-file coverage.info

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo program compiled successfully
