sudo: required
language: c
os:
  - linux
compiler:
  - gcc

script:
  - gcc -std=c99  csv.c list.c list.h csv.h -coverage
  - ./a.out
  - gcov -o  csv.c list.c
  - echo program compiled successfully

after_success:
  - bash <(curl -s https://codecov.io/bash)