sudo: required
language: c
os:
  - linux
compiler:
  - gcc

script:
  - gcc -std=c99 tests.c csv.c list.c list.h csv.h -coverage -lcheck
  - ./a.out
  - gcov -o tests.c csv.c list.c list.h csv.h
  - echo program compiled successfully

after_success:
  - bash <(curl -s https://codecov.io/bash)