before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq [packages list]

sudo: required
language: c
os:
  - linux
compiler:
  - gcc


script:
  - gcc -std=c99  csv.c lib.a -coverage
  - ./a.out
  - gcov -c  csv.c list.c tests.c


after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo program compiled successfully